version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 1
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
          - "zone.js"
      angular-eslint:
        patterns:
          - "@angular-eslint/*"
          - "angular-eslint"
