name: lint test ✨

on:
  push:
  pull_request:

env:
  NODE_VERSION: 20

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: lint
        run: |
          npm install
          npm run lint

      - name: test
        run: npm run test:headless
