name: lint test ✨

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/fermium, lts/gallium] # support the 2 latest lts versions

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - name: lint
      run: |
        npm install
        npm run lint
        npm run lint:format

    - name: test
      run: npm run test:headless
