name: Lint & Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5

      - name: Read Node.js version from .node-version
        run: echo "NODE_VERSION=$(cat .node-version)" >> $GITHUB_OUTPUT
        id: node-version

      - uses: pnpm/action-setup@v6

      - name: Use Node.js ${{ steps.node-version.outputs.NODE_VERSION }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ steps.node-version.outputs.NODE_VERSION }}
          cache: pnpm

      - name: Lint
        run: |
          pnpm install --frozen-lockfile
          pnpm format:check
          pnpm lint

      - name: Test
        run: pnpm test:ci
